// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package admin

import (
	"go-zentao-task/model/admin"
)

// Injectors from wire.go:

func InitializeService() *Service {
	intf := admin.NewInf()
	user := admin.NewUser()
	role := admin.NewRole()
	menu := admin.NewMenu()
	roleMenu := admin.NewRoleMenu()
	service := NewService(intf, user, role, menu, roleMenu)
	return service
}

// wire.go:

type Service struct {
	Intf     *admin.Intf
	User     *admin.User
	Role     *admin.Role
	Menu     *admin.Menu
	RoleMenu *admin.RoleMenu
}

func NewService(
	intf *admin.Intf,
	user *admin.User,
	role *admin.Role,
	menu *admin.Menu,
	roleMenu *admin.RoleMenu) *Service {
	return &Service{
		Intf:     intf,
		User:     user,
		Role:     role,
		Menu:     menu,
		RoleMenu: roleMenu,
	}
}
